image: continuumio/miniconda3:latest

before_script:
  - apt-get update
  - apt-get install -y cmake
  - apt-get install -y gcc
  - which cmake
  - which gcc
  - conda env create -n _env python=3.7 -f requirements/conda.txt
  - source activate _env
  - python -m pip install conan


stages:
  - build
  - test


build:
  script:
    - cd nativelib/scripts
    - bash ./build.sh
    - cd $CI_PROJECT_DIR
    - python setup.py build_ext --inplace


test:
  script:
    - pytest tests -v