
stages:
  - docker
  - conda
  - build
  - test
  - package


Docker build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind # requirement for docker build
  rules:
    - changes:
        - ci-image/*
      when: always
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      -t $CI_REGISTRY_IMAGE:latest
      ./ci-image
    - docker push $CI_REGISTRY_IMAGE:latest

conda setup:
  image: $CI_REGISTRY_IMAGE:latest
  stage: conda
#  rules:
#      - changes:
#        - requirements/conda.txt
#        when: always
  script:
    - conda env create -p ~/conda_env python=3.7 -f requirements/conda.txt
    - source activate ~/conda_env
    - python -m pip install conan
    - conan --version
    - cython --version
  cache:
    paths:
      - ~/conda_env/*
    key: ${CI_COMMIT_REF_SLUG}


build-cpp:
  image: $CI_REGISTRY_IMAGE:latest
  stage: build
  script:
    - cd nativelib/scripts
    - bash ./build_clang_6.sh
  cache:
    untracked: true
    paths:
      - ~/conda_env/*
      - $CI_PROJECT_DIR/pylib/*
    key: ${CI_COMMIT_REF_SLUG}


build-cython:
  image: $CI_REGISTRY_IMAGE:latest
  stage: build
  script:
    - source activate ~/conda_env
    - python setup.py build_ext --inplace
  cache:
    untracked: true
    paths:
      - ~/conda_env/*
      - $CI_PROJECT_DIR/*
    key: ${CI_COMMIT_REF_SLUG}


test:all:
  image: $CI_REGISTRY_IMAGE:latest
  stage: test
  variables:
    PYTHONPATH: .
  script:
    - find pylib/
    - source activate ~/conda_env
    - pytest tests -v
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/conda_env
      - $CI_PROJECT_DIR/*


package-all:
  stage: package
  script:
    - find pylib

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $CI_PROJECT_DIR/*

  artifacts:
    paths:
      - $CI_PROJECT_DIR/pylib
    expire_in: 30 days