image: continuumio/miniconda3:latest

before_script:
  - pip install conan
  - apt-get install clang cmake -y
  - conda create -n _env python=3.7 -f requirements/conda.txt
  - source activate _env

build:
  script:
    - cd scripts
    - ./build.sh

